### ISSUE TITLE
cumulatively addable vs addable

### ISSUE THREAD

**Issue by robertramey** [taocpp/operators#2]
I'm looking at this project as I have a good use for it.  I'm not seeing one thing though.  It seems to me that cumulatively addable an addable have the same results and requirements.  That is I'm not seeing any difference between them.

My interest is in using a + b as the requirement so that I can use with types which don't support the += operator.  That is immutable types.

Thanks in advance

Robert Ramey

PS Have you considered adding this to the Boost Library Incubator?

**Comment by d-frey** [comment]
Are you referring to "commutative" instead of "cumulative"? In that case there is a paragraph in the documentation which explains the difference and why you should prefer the commutative version when possible: https://github.com/d-frey/operators#commutativity

For immutable types, I don't see how an operator library can help. When += is not available, the class must provide operator+, which leaves nothing to generate for a library. Or is there some case I'm missing? If you could provide an example, I'd be happy to have a look at it.

For adding it to the Boost Library Incubator: I am the maintainer of the Boost.Operators library. :) That said, the df.Operators library caused quite some controversy in the past over its use of rvalue-references as return values. OTOH, that is why it can avoid more temporaries than the traditional approach. I should probably add a paragraph to the documentation to explain that point in more detail, I'll try to find some time at the weekend.

Your message also reminds me to come up with a plan to finally advance this project to a point where it can be (partly) incorporated back into Boost.Operators. Let's see if I can see a reasonable way :)

**Comment by d-frey** [comment]
Robert, is your question answered? Otherwise, please re-open and elaborate, thanks.
